### ISSUE TITLE
Implicit tuple unpack

### ISSUE THREAD

**Issue by momohatt** [egison/egison#100]
Maybe the second one should raise type error?
```
> ((lambda [$x $y] (+ x y)) 1 2)
3
> ((lambda [$x $y] (+ x y)) [1 2])
3
```

**Comment by egisatoshi** [comment]
In fact, it is the specification of Egison.

`((lambda [$x $y] (+ x y)) 1 2)` is a kind of syntax sugar of `((lambda [$x $y] (+ x y)) [1 2])`, though there is a possibility that this specification will change if we support Currying as Haskell in future.

**Comment by momohatt** [comment]
Right, but I think this can be confusing to normal functional programmers, as noted by one of the users...:
https://nekketsuuu.github.io/entries/2018/09/19/egison.html
