### ISSUE TITLE
Improve granularity of files

### ISSUE THREAD

**Issue by momohatt** [egison/egison#108]
During the development, Types.hs gets changed often. However, it consists of about 2000 lines of code and takes longer to compile than other files.

Current Types.hs contains not only type-related definitions but also functions for arithmetic and tensor operations. We can move it into another new file for the sake of faster compilation and readability.

**Comment by momohatt** [comment]
Changed the title of this issue since I think this problem holds for other files as well.

**Comment by egisatoshi** [comment]
I split MathExpr.hs and Tensor.hs from Types.hs.

**Comment by momohatt** [comment]
Thanks a lot! Do you think we can do the same for Core.hs?

**Comment by egisatoshi** [comment]
I think it is difficult for Core.hs because evalExpr uses patternMatch and patternMatch uses evalExpr.
But, there is a possibility that we can move some functions from Core.hs to other modules.
Let me think.
