### ISSUE TITLE
regex-cg not working as expected

### ISSUE THREAD

**Issue by momohatt** [egison/egison#114]
The following code, which is taken from https://www.egison.org/manual/primitive-functions.html#demo-regex-cg , does not work as expected.

```
> (regex-cg "[0-9]+,[0-9]+" "abc,123,45,defg")
{["abc," {} ",defg"]}
```

**Comment by momohatt** [comment]
Also, the following code is expected to return `{["" "" ""]}` ?

```
> (regex "[a]*" "")
{}
```

**Comment by egisatoshi** [comment]
Thank you very much!
I fixed the manual as follows (inserted parenthesis):
```
(regex-cg "([0-9]+),([0-9]+)" "abc,123,45,defg");=>{["abc," {"123" "45"} ",defg"]}
```

I also fixed the implementation of the `regex` function.
```
> (regex "[a]*" "")
{["" "" ""]}
```

**Comment by momohatt** [comment]
Looks great, thanks!
