### ISSUE TITLE
Rewrite the tests of sample programs to use assert

### ISSUE THREAD

**Issue by egisatoshi** [egison/egison#117]
For each of the sample programs used in the tests,:
https://github.com/egison/egison/blob/d1071afc145529a43eee850c2d7e80ff45cbb79d/test/Test.hs#L53-L61
rewrite them to use `assert` or `assert-equal` with the expected answers prepared under test/answer/ directory.

**Comment by momohatt** [comment]
(As for the math sample programs, I didn't know the best label names to put to each test cases)
