### ISSUE TITLE
anonymous recursive function

### ISSUE THREAD

**Issue by egisatoshi** [egison/egison#118]
The following program returns error.
```
(take 10 (1#{%1 @(# (* %1 2))} 2))
```

The reason is that the symbol `#` is newly used for "fresh variables", which are often used for tensor indices.

**Comment by momohatt** [comment]
Maybe writing `%0` instead of `#` like as follows will solve the problem?
```
> (take 10 (1#{%1 @(%0 (* %1 2))} 2))
{2 4 8 16 32 64 128 256 512 1024}
```

**Comment by momohatt** [comment]
By the way I found a bug. The following expression is expected to be equal with the above one, but it doesn't return.
```
> (take 10 (1#(cons %1 (%0 (* %1 2))) 2))
```
