### ISSUE TITLE
Wedge expression does not work inside of function?

### ISSUE THREAD

**Issue by momohatt** [egison/egison#128]
```
> ((lambda [$x $y] !(+ x y)) [| 1 2 3 |] [| 1 2 3 |])
[| 2 4 6 |]
```

However this result is expected to be equal to:
```
> !(+ [| 1 2 3 |] [| 1 2 3 |])
[| [| 2 3 4 |] [| 3 4 5 |] [| 4 5 6 |] |]
```

**Comment by egisatoshi** [comment]
It is correct behavior because `$x` and `$y` are scalar parameters and `x` and `y` are bound to tensor components (not tensors themselves).

If we change the scalar parameters to tensor parameters, the wedge expression works as we expected.
```
> ((lambda [%x %y] !(+ x y)) [| 1 2 3 |] [| 1 2 3 |])
[| [| 2 3 4 |] [| 3 4 5 |] [| 4 5 6 |] |]
```

**Comment by momohatt** [comment]
I see, thanks!
