### ISSUE TITLE
Evaluate again after substitution

### ISSUE THREAD

**Issue by egisatoshi** [egison/egison#130]
```
(substituite {[x 0]} (exp x)) ;=> NG: (exp 0); OK: 1
```

**Comment by momohatt** [comment]
@egisatoshi Can you elaborate on this issue?

**Comment by egisatoshi** [comment]
The current implementation of the `substitute` function just substitute symbols and does not evaluate or rewrite the expressions again.
```
substitute [(x, 0)] (exp x)
-- returns "exp 0", though we want to return "1".

substitute [(x, i)] (x^2)
-- returns "i^2", though we want to return "-1".
```
We want to improve this behavior in some way.

**Comment by momohatt** [comment]
Just replacing the following `mExpr` with `mathNormalize mExpr` would be enough?
https://github.com/egison/egison/blob/a63ee1545c8330e50a878300c17325ce8e0810be/lib/math/expression.egi#L292

**Comment by egisatoshi** [comment]
Thank you for the idea!
I think It would be enough.
