### ISSUE TITLE
Implement currying

### ISSUE THREAD

**Issue by egisatoshi** [egison/egison#131]
```
(define $f (lambda [$x $y] (+ x y))

((f 1) 2) ; 3
```

**Comment by momohatt** [comment]
With #210, the following would work.
```hs
f x y := x + y
(f 1) 2 -- 3
```
However, the following won't work.
```hs
f x y := x + y
f 1 2 3 -- error
```
I don't know if the latter one should work because for unary functions, arguments are packed into one tuple.
```hs
f x := x
f 1 2 3 -- (1, 2, 3)
```
