### ISSUE TITLE
Why do primitive matchers default to eq?

### ISSUE THREAD

**Issue by noprompt** [egison/egison#141]
I recently implemented the Egison pattern matcher in Clojure following the instructions given in the paper "Scheme Macros for Non-linear Pattern Matching with Backtracking for Non-free Data Types." I found the process of putting together the Egison pattern matcher fairly simple, however, was confused with some of the behavior of the matcher.

At the moment the `integer` matcher I created works as follows.

```clj
(match-all "foo" integer [x x])
;; => ()
```

The code behind this matcher is simple.

```clj
(defn integer [p t]
  (if (integer? t)
    (if (integer? p)
      (if (= t p)
        `(())
        ())
      `((~[p Something t])))
    ()))
```

Yet, in Egison the behavior is different.

```egi
(match-all "foo" integer {[$x x]})
;; => {"foo"}
```

I took a look at `base.egi` to see how the `integer` matcher was defined and noticed that it define as `eq`. This surprised me because many of the tests and documentation seem to hint at the `integer` matcher being intended to match only integer targets. On Page 8 of "Non-linear Pattern Matching with Backtracking for Non-free Data Types" it says

> ... `(list integer)` is a matcher to pattern-match the pattern and target as a list of integer.

so my assumption is that something like

```egi
(match-all {"foo" "bar"} (list integer) {[<cons $x $xs> [x xs]]})
;; => {["foo" {"bar"}]}
```

should fail to match.

So my question is: is this the intended behavior? If so, why? If not, what is the plan?

---

Also, thank you @egisatoshi for your publications. I have been following your work for some time in this space and have enjoyed it.

**Comment by noprompt** [comment]
I forgot to mention that I am interested in this because I would like to open source my implementation of the Egison matcher in Clojure; I would perhaps even like to contribute it. However, I would like to be sure the work I am doing is correct.

**Comment by egisatoshi** [comment]
Thank you very much for your issue, for reading our paper, and importing Egison to Clojure!

Currently, Egison does not care about error checking (including type checking) and expects users to always write correct code.
This is the reason why the `integer` matcher is currently just an alias of the `eq` matcher.

However, I am planning to change this situation by introducing a static type system to Egison.
A static type system allows typing `eq` and `integer` differently for detecting incorrect usage of `integer` like your last sample.
In fact, in the Haskell implementation of Egison pattern matching, the `Eql` matcher (`eq` in Haskell) and the `Integer` matcher implementation are distinguished.
The following lines declare that `Eql` and `Integer` is a matcher for the data types that are instances of the `Eq` and `Integral` type class, respectively.

Eql: https://github.com/egison/egison-haskell/blob/master/src/Control/Egison/Matcher.hs#L45
Integer: https://github.com/egison/egison-haskell/blob/master/src/Control/Egison/Matcher.hs#L53

Here is a presentation material on this Haskell implementation.
p55 and p56 are related to this topic.

https://www.egison.org/download/20191109HaskellDay.pdf

**Comment by noprompt** [comment]
Thanks for your prompt reply!

Since you have plans to address the typing issue, would you consider it a safe move for me to implement the behavior of, for example, `(list integer)` in Clojure as follows?

```clj
(match-all '(1 "foo") (list integer)
  [x x])
;; => ()
```

Currently, my implementation will return `((1 "foo"))` for the result set in this example. I am able to easily make the implementation return `()`.

**Comment by egisatoshi** [comment]
I feel there is no problem if the `integer` matcher does not allow to bind a string to a pattern variable as you proposed,

```
(match-all "str" integer [x x])
; => ()
```

though I feel producing the type error is the best solution, if it is possible.

```
(match-all "str" integer [x x])
; => type error: integer cannot match a string "str".
```
