### ISSUE TITLE
Parse a pattern function without arguments

### ISSUE THREAD

**Issue by egisatoshi** [egison/egison#154]
The code is taken from `nons-lib/core/maybe.egi`.
```
nothing := \ => []
```

**Comment by momohatt** [comment]
Thanks! I think it should rather be pretty-printed like as follows:
```
nothing := \() => []
```

**Comment by egisatoshi** [comment]
Thank you! It sounds good!

**Comment by momohatt** [comment]
Fixed in 2bd1b35915a6308c960561c545d44e139060894b.
