### ISSUE TITLE
Coexistence of scalar parameters and lazy evaluation

### ISSUE THREAD

**Issue by egisatoshi** [egison/egison#158]
The arguments of `::` is scalar parameters and `::` evaluates its arguments to WHNF before applying them.
Therefore, the following program does not work.
```
nats := 1 :: map (\n -> n + 1) nats

take 3 nats
-- infinite loop
```

**Comment by momohatt** [comment]
At least we could solve the above problem by parsing `x :: y` as `{x @y}` and not `(cons x y)`. (I'm aware that this doesn't solve the problem in general though.)

**Comment by egisatoshi** [comment]
I decided to make tensor parameters default instead of scalar parameters.
We need to take care of not only `::` but also high-order functions such as `map` and `foldl`.
```
map M.det [ [| [| 1, 0 |], [| 0, 1 |] |] ]
foldl (.) [| [| 1, 0 |], [| 0, 1 |] |]  [ [| [| 1, 0 |], [| 0, 1 |] |] ]
```

**Comment by momohatt** [comment]
I started the development of making default argument type to `TensorArg` in https://github.com/egison/egison/tree/tensor-arg , but maybe I'll finish #133 first and get back to this later.
