### ISSUE TITLE
Non-exhaustive patterns in case on egison-translate

### ISSUE THREAD

**Issue by theoremoon** [egison/egison#176]
When I did `stack exec -- egison-translate ~/github.com/greymd/egzact/bin/addb.egi`, then the following caution was showed.  I think some cases are missed. please fix it. 

```
egison-translate: hs-src/Language/Egison/Parser/SExpr.hs:(213,3)-(214,52): Non-exhaustive patterns in case
```

Unluckily, I don't good at both egison and haskell. So I just reported this issue. 

Thanks.

**Comment by momohatt** [comment]
Thanks for the bug report!
The failure was caused because we forgot to take care of the shebang, but I fixed it now.
