### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by sasagawa888** [egison/egison#273]
はじめまして。笹川といいます。メールがつながらなかったのでここに書くことにしました。
リーマン幾何学に興味があり検索していたところEgison言語のことを
知りました。インストールを試みているのですがうまくいきません。

UbuntuとLinux-MINTで試しました。いずれもエラーになります。

次のようにターミナルに表示されます。
何が原因でしょうか？

ご教示よろしくお願いします。

笹川

cabal install egison egison-tutorial
Warning: The install command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-install
command or the legacy v1-install alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Resolving dependencies...
Starting     egison-4.1.2
Building     egison-4.1.2
Failed to install egison-4.1.2
Build log ( /home/sasagawa/.cabal/logs/ghc-8.6.5/egison-4.1.2-GEmLMV3JhMS3MvJ3f3mWZT.log ):
cabal: Entering directory '/tmp/cabal-tmp-438/egison-4.1.2'
Configuring egison-4.1.2...
Preprocessing library for egison-4.1.2..
Building library for egison-4.1.2..
[ 1 of 38] Compiling Language.Egison.AST

**Comment by greymd** [comment]
こんにちは、Egisonのビルド周りのメンテをしている山田です。
下記のように `v2-install` としたらいかがでしょう？

`cabal v2-install egison`

`cabal`のバージョンによってはビルドがうまく動作しないことがあるようです。

**Comment by egisatoshi** [comment]
Ubuntuであれば @greymd さんが用意してくれたコンパイル済みのインストーラーがあります．
そちらもぜひ試してみてください．

https://egison.readthedocs.io/en/latest/reference/install.html

**Comment by sasagawa888** [comment]
cabalのメッセージにv1とあったので次のようにやってみました。
cabal v1-install egison egison-tutorial

途中まではうまくいくのですが、最後に次のエラーがでます。

hs-src/Language/Egison/Data.hs:520:30: error:
    Not in scope: type constructor or class ‘MonadFail’
    Perhaps you meant ‘MonadFix’ (imported from Control.Monad.Except)
    |
520 | instance {-# OVERLAPPING #-} MonadFail EvalM where
    |                              ^^^^^^^^^
cabal: Leaving directory '/tmp/cabal-tmp-667/egison-4.1.2'
cabal: Error: some packages failed to install:
egison-4.1.2-GEmLMV3JhMS3MvJ3f3mWZT failed during the building phase. The
exception was:
ExitFailure 1
egison-tutorial-4.0.1-Gzff3smDzVP2cfaY8RLVZE depends on egison-tutorial-4.0.1
which failed to install.

**Comment by sasagawa888** [comment]
パッケージマネージャを使ったらうまくいきました。
dpkg
$ wget https://git.io/egison.x86_64.deb https://git.io/egison-tutorial.x86_64.deb
$ sudo dpkg -i ./egison*.deb

$ egison
Egison Version 4.1.2
https://www.egison.org
Welcome to Egison Interpreter!
> 

ありがとうございました。
