### ISSUE TITLE
symbolic calculation

### ISSUE THREAD

**Issue by sasagawa888** [egison/egison#274]
Egisonの入門ページを見つつ次の入力をしたところ、説明と違う結果となりました。
バージョンが違うのでしょうか？ご教示ください。

egison
Egison Version 4.1.2
https://www.egison.org
Welcome to Egison Interpreter!
> (* (+ x y) (+ x y))
#<lambda ["$_95"] ...>
> (** (+ 1 i) 5)
Parse error at: egison:1:3:
  |
1 | (** (+ 1 i) 5)
  |   ^
unexpected '*'
expecting infix

> 

参考にしたのは下記のページです。
https://www.egison.org/ja/math.html

**Comment by egisatoshi** [comment]
すみません．そちらのページの情報が古くなってしまっているので，こちらのマニュアルを参考にしてみてください．

https://www.egison.org/download/manual.pdf

**Comment by sasagawa888** [comment]
解決しました。早速のご回答ありがとうございます。
