### ISSUE TITLE
egison-tutorial problem

### ISSUE THREAD

**Issue by freakhill** [egison/egison#66]
Hello, when I try the tutorial, one of the examples seems to block.

Am I doing something wrong?

![2016-11-14 13_41_39-](https://cloud.githubusercontent.com/assets/916582/20253597/358007fe-aa70-11e6-9a2d-1aa98d12e600.png)

**Comment by freakhill** [comment]
here too

![egi](https://cloud.githubusercontent.com/assets/916582/20254227/c9341f1c-aa75-11e6-85cf-016627d5954b.png)

**Comment by freakhill** [comment]
consequently
![egi2](https://cloud.githubusercontent.com/assets/916582/20254250/f8d450ac-aa75-11e6-943c-de49ace4b250.png)

**Comment by egisatoshi** [comment]
Thank you for your report!

The first block seems Egison's bug.
I'll fix it.

The reason of the second and third errors is egison-tutorial is for the older version of Egison interpreter.
I'll update it soon.

**Comment by egisatoshi** [comment]
I fixed them.
Please install egison-tutorial-3.6.2 and try it again!

Thanks!
