### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by abeq** [egison/egison#67]
<add>

Followed message has been displayed on console (not in log).
cabal: Error: some packages failed to install:
egison-3.6.3 failed during the building phase. The exception was:
ExitFailure 1
egison-tutorial-3.6.2 depends on egison-3.6.3 which failed to install.

</add>
---
I have try to install egison with https://www.egison.org/ja/getting-started/getting-started-mac.html, but error has occurred.
Please check it and advise me to fix it.

- OS version: 10.10.5
- Haskell Platform version: 8.0.1
- egison version: 3.6.3

1. brew cask install haskel-platform 
2. cabal update and then cabal install egison egison-tutorial

log:
cabal: Entering directory '/var/folders/_6/qp3ctywx2yb7rgcgp0l9hs_40000gn/T/cabal-tmp-85684/egison-3.6.3'
Configuring egison-3.6.3...
Building egison-3.6.3...
Preprocessing library egison-3.6.3...
[1 of 8] Compiling Language.Egison.Types ( hs-src/Language/Egison/Types.hs, dist/build/Language/Egison/Types.o )

hs-src/Language/Egison/Types.hs:150:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use Control.Monad.Except instead

hs-src/Language/Egison/Types.hs:700:29: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Types.hs:733:25: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Types.hs:959:28: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Types.hs:1448:10: warning: [-Wdeprecations]
    In the use of type constructor or class ‘Error’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Types.hs:1448:10: warning: [-Wdeprecations]
    In the use of type constructor or class ‘Error’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Types.hs:1460:18: warning: [-Wdeprecations]
    In the use of type constructor or class ‘ErrorT’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Types.hs:1464:14: warning: [-Wdeprecations]
    In the use of ‘runErrorT’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Types.hs:1467:27: warning: [-Wdeprecations]
    In the use of data constructor ‘ErrorT’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Types.hs:1515:25: warning: [-Wdeprecations]
    In the use of type constructor or class ‘Error’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Types.hs:1515:49: warning: [-Wdeprecations]
    In the use of type constructor or class ‘ErrorT’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
[2 of 8] Compiling Language.Egison.Desugar ( hs-src/Language/Egison/Desugar.hs, dist/build/Language/Egison/Desugar.o )

hs-src/Language/Egison/Desugar.hs:28:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use Control.Monad.Except instead

hs-src/Language/Egison/Desugar.hs:34:62: warning: [-Wdeprecations]
    In the use of type constructor or class ‘ErrorT’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Desugar.hs:38:15: warning: [-Wdeprecations]
    In the use of ‘runErrorT’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
[3 of 8] Compiling Paths_egison     ( dist/build/autogen/Paths_egison.hs, dist/build/Paths_egison.o )
[4 of 8] Compiling Language.Egison.Parser ( hs-src/Language/Egison/Parser.hs, dist/build/Language/Egison/Parser.o )

hs-src/Language/Egison/Parser.hs:29:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use Control.Monad.Except instead

hs-src/Language/Egison/Parser.hs:101:35: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
[5 of 8] Compiling Language.Egison.Core ( hs-src/Language/Egison/Core.hs, dist/build/Language/Egison/Core.o )

hs-src/Language/Egison/Core.hs:46:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use Control.Monad.Except instead

hs-src/Language/Egison/Core.hs:129:30: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Core.hs:130:34: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Core.hs:468:42: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Core.hs:971:30: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Core.hs:1014:28: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Core.hs:1060:32: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Core.hs:1096:47: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Core.hs:1101:56: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Core.hs:1107:31: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Core.hs:1131:37: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

hs-src/Language/Egison/Core.hs:1132:37: warning: [-Wdeprecations]
    In the use of ‘strMsg’
    (imported from Control.Monad.Error, but defined in Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
[6 of 8] Compiling Language.Egison.Primitives ( hs-src/Language/Egison/Primitives.hs, dist/build/Language/Egison/Primitives.o )

hs-src/Language/Egison/Primitives.hs:14:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use Control.Monad.Except instead
[7 of 8] Compiling Language.Egison.Util ( hs-src/Language/Egison/Util.hs, dist/build/Language/Egison/Util.o )

hs-src/Language/Egison/Util.hs:14:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Error’ is deprecated:
      Use Control.Monad.Except instead
[8 of 8] Compiling Language.Egison  ( hs-src/Language/Egison.hs, dist/build/Language/Egison.o )
ghc: unrecognised flag: --enable-profiling

Usage: For basic information, try the `--help' option.
cabal: Leaving directory '/var/folders/_6/qp3ctywx2yb7rgcgp0l9hs_40000gn/T/cabal-tmp-85684/egison-3.6.3'

**Comment by vintersnow** [comment]
Same issue here.

**Comment by egisatoshi** [comment]
Thank you for your issue and sorry for late response.

I upadated the package. Would you try the installation again?

(I cannot get the same error on my Mac...)

**Comment by vintersnow** [comment]
I succeed to install : )
Thank you!
