### ISSUE TITLE
Calculation of float number does not work.

### ISSUE THREAD

**Issue by greymd** [egison/egison#68]
Hi,
It seems that any float number can not be processed.
```
$ egison --version
3.7.0

$ egison
> (+ 1.1 4)
Expected number, but found: 1.1
```

Even the old version of Egison works like this.

```
$ docker run -it egison/egison
Egison Version 3.5.6 (C) 2011-2014 Satoshi Egi
http://www.egison.org
Welcome to Egison Interpreter!
> (+ 1.1 4)
5.1
```

**Comment by egisatoshi** [comment]
Actually, `+` for float number is temporarily changed to `f.+`.
I will reverse it to `+` in the next release.

**Comment by greymd** [comment]
Oh I see. Thanks!
