### ISSUE TITLE
Randomized real numbers

### ISSUE THREAD

**Issue by vmchale** [egison/egison#92]
Hi,

Is it currently possible to generate random floats/real numbers?

As an example in Python:

```
>>> import numpy as np
>>> np.random.random((3,1))
array([[0.92423704],
       [0.79431525],
       [0.63689893]])
```

(this is useful to seed training of a neural network, among other things)

Thanks :)

**Comment by egisatoshi** [comment]
Hi @vmchale 

Currently, we do not support random real numbers.
But, I will implement it today.

Thanks :)

**Comment by egisatoshi** [comment]
Egison version 3.9.1 supports random real numbers.
Enjoy!

https://github.com/egison/egison/releases/tag/3.9.1

Tensor index notation of Egison makes a program for neural network concise.
(Maybe, you have the same idea?)
It will be interesting if we try that.
